language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - chmod 777 tests/temp

script:
    - ./tests/run-tests.sh
