#!/bin/bash

DIR=`pwd`/`dirname $0`;

cd $DIR/..
composer install --no-interaction --prefer-source
cd -

ARGUMENTS='';
if [ "$1" == "" ]; then
	ARGUMENTS="-p php $DIR/src"
else
	ARGUMENTS=$@
fi

$DIR/../vendor/bin/tester -s -j 3 -c $DIR/config/php.ini --colors 1 $ARGUMENTS