#!/bin/bash

DIR=`dirname $0`;

cd $DIR/..
rm composer.lock
composer install --no-interaction --prefer-source
cd -

PHP_VERSION=`php -r 'echo PHP_MAJOR_VERSION . "." . PHP_MINOR_VERSION;'`

TEMP_DIR=$DIR/temp
rm -rf $TEMP_DIR/*
mkdir -p $TEMP_DIR/cache/latte

$DIR/../vendor/bin/tester -p php $DIR -s -j 5 --colors 1 -c $DIR/config/php-$PHP_VERSION-unix.ini